import type { Metadata } from "next";
import Link from "next/link";
import { pageMetadata } from "../../../_lib/metadata";
import { LegalCallout, LegalDocument, LegalSection } from "../legal-components";

export const metadata: Metadata = pageMetadata({
  title: "Service terms",
  description:
    "Commercial terms for a RemainFrame private U.S. business pilot when expressly incorporated into an executed Order Form or fixed-version clickwrap.",
  path: "/remainframe/legal/service-terms",
  type: "article",
});

const toc = [
  { id: "binding", label: "How these terms become binding" },
  { id: "definitions", label: "Definitions and precedence" },
  { id: "eligibility", label: "Business use and accounts" },
  { id: "service", label: "Pilot service" },
  { id: "byok", label: "BYOK and third-party providers" },
  { id: "data", label: "Customer Content and data roles" },
  { id: "ip", label: "Intellectual property and outputs" },
  { id: "responsible-use", label: "Responsible use and human review" },
  { id: "support-security", label: "Support, security, and incidents" },
  { id: "confidentiality", label: "Mutual confidentiality" },
  { id: "fees", label: "Fees, renewal, and taxes" },
  { id: "term", label: "Term, suspension, and termination" },
  { id: "return", label: "Return, deletion, and export" },
  { id: "warranties", label: "Warranties and disclaimers" },
  { id: "indemnity", label: "Customer indemnity" },
  { id: "liability", label: "Liability limits" },
  { id: "law", label: "Law, venue, and jury waiver" },
  { id: "general", label: "General terms and notices" },
] as const;

export default function ServiceTermsPage() {
  return (
    <LegalDocument
      title="Service terms"
      summary="These terms are a fixed public form for the private RemainFrame business pilot. They govern a customer only when the contracting mechanism below expressly incorporates them."
      toc={toc}
    >
      <LegalSection id="binding" title="1. How these terms become binding">
        <p>
          These Service Terms become a binding agreement only when either:
        </p>
        <ol>
          <li>
            the customer and the provider identified in an Order Form sign that Order
            Form and it expressly incorporates the July 20, 2026 version of these Service
            Terms by title and URL; or
          </li>
          <li>
            an authorized customer representative completes a true clickwrap flow that
            clearly displays these Service Terms, identifies this fixed version, requires
            an affirmative act of agreement, and preserves evidence of that agreement.
          </li>
        </ol>
        <p>
          A footer link, website visit, demo, trial conversation, email exchange, pilot
          application, or access supplied for evaluation does not by itself incorporate
          these Service Terms. The exact contracting provider legal name and notice
          address must appear in the signed Order Form or clickwrap record. That
          identified party is the <strong>Provider</strong>. The business entering the
          agreement is the <strong>Customer</strong>.
        </p>
        <LegalCallout title="No customer activation yet.">
          <p>
            RemainFrame is in a private proving-ground stage. These terms are written for
            an eventual authorized pilot, but publication does not mean a customer has
            been activated or that paid service is generally available.
          </p>
        </LegalCallout>
      </LegalSection>

      <LegalSection id="definitions" title="2. Definitions and order of precedence">
        <p>
          <strong>Agreement</strong> means the executed Order Form, these Service Terms,
          any incorporated Data Processing Addendum, and the Acceptable Use Policy.
          <strong> Authorized User</strong> means an adult employee, contractor, or other
          individual whom Customer authorizes to use the Service for Customer&apos;s
          internal business. <strong>Customer Content</strong> means data, prompts,
          messages, files, context, instructions, credentials, tool inputs, and other
          material submitted to or retrieved by the Service for Customer.{" "}
          <strong>Output</strong> means content generated by or returned through the
          Service in response to Customer Content. <strong>Service</strong> means the
          RemainFrame configuration identified in the Order Form.
        </p>
        <p>If documents conflict, the following order applies:</p>
        <ol>
          <li>
            the Order Form, but only where it expressly identifies the provision it
            overrides;
          </li>
          <li>
            the DPA, solely for the processing and protection of Customer Personal Data;
          </li>
          <li>these Service Terms;</li>
          <li>the Acceptable Use Policy; and</li>
          <li>other documentation or policies expressly incorporated by the Order Form.</li>
        </ol>
        <p>
          A purchase order, vendor portal term, or Customer form does not modify the
          Agreement unless the Provider expressly signs an amendment that identifies the
          change. Headings are for convenience and do not affect interpretation.
        </p>
      </LegalSection>

      <LegalSection id="eligibility" title="3. Business use and accounts">
        <p>
          The Service is offered only to U.S. businesses for use in the United States by
          Authorized Users who are at least 18. It is not a consumer service. The person
          accepting the Agreement for Customer represents that they have authority to do
          so.
        </p>
        <p>
          Customer is responsible for selecting Authorized Users, maintaining accurate
          account and contact information, assigning least-privilege access, promptly
          removing access when no longer needed, protecting authentication methods, and
          all activity under its accounts except to the extent caused by Provider&apos;s
          breach of the Agreement.
        </p>
        <p>
          Customer must promptly report suspected unauthorized access. Accounts and
          access methods may not be shared outside the authorized business relationship,
          resold, leased, or used to provide a bureau or managed service unless the Order
          Form expressly allows it.
        </p>
      </LegalSection>

      <LegalSection id="service" title="4. Private pilot service">
        <p>
          Provider will make the Service identified in the Order Form available during
          the subscription or pilot term, subject to the Agreement. The Order Form must
          state the enabled channels, model and tool configuration, support boundaries,
          included work, fees, and any customer-specific limits.
        </p>
        <p>
          The current proving ground uses an approved messaging channel, the private
          RemainFrame runtime, self-hosted Honcho memory, OpenRouter, customer-selected
          model endpoints, authorized MCP servers or tools, and a VPS hosted on
          Hostinger. Self-hosted Langfuse may be used as an internal observability
          component when identified in the approved configuration. This description does
          not promise every component in every Order Form.
        </p>
        <p>
          The pilot is evolving. Universal integrations, self-service activation,
          service-wide selective privacy tooling, and a fully verified self-service
          export are not shipped. Provider may improve or replace components if the
          change does not materially reduce the expressly purchased core functionality,
          weaken agreed data protections, or add a new processor without following the
          DPA.
        </p>
        <p>
          Pilot, beta, preview, and evaluation features are pre-release, may change or be
          withdrawn, and may have additional limits identified in the Order Form. They
          may not be used for production-critical work unless the Order Form expressly
          approves that use and its safeguards.
        </p>
        <p>
          The current early-stage service has no uptime, response-time, recovery-time, service-level,
          or service-credit commitment. Non-guaranteed support targets may be stated for
          planning only. Planned features, roadmaps, demos, examples, and status labels
          are informational and not commitments.
        </p>
      </LegalSection>

      <LegalSection id="byok" title="5. Customer keys and third-party providers">
        <p>
          The current pilot uses a bring-your-own-key model. Customer selects and
          maintains its model, routing, messaging, and connected-tool accounts and
          provides credentials through the approved setup path. Customer is responsible
          for confirming that its selections, account settings, usage limits, data
          controls, and provider terms are suitable for its use.
        </p>
        <p>
          Customer-selected model endpoints receive the prompts, instructions, context,
          and related data reasonably needed to generate a response. Signal and
          connected tools receive data reasonably necessary for their role. OpenRouter
          may receive relevant request and routing data when Customer selects it. Each
          provider&apos;s retention, training, location, security, availability, and
          content rules may differ and are governed by Customer&apos;s relationship with
          that provider unless the Order Form expressly says otherwise.
        </p>
        <p>
          Customer pays provider fees and overages directly unless the Order Form
          expressly includes them. Provider is not responsible for third-party price
          changes, exhausted credits, account suspension, model changes, output policy,
          or downtime outside Provider&apos;s reasonable control. Provider may decline a
          configuration that does not pass the activation review.
        </p>
      </LegalSection>

      <LegalSection id="data" title="6. Customer Content, data rights, and instructions">
        <p>
          As between the parties, Customer retains its rights in Customer Content.
          Customer grants Provider and its approved subprocessors a nonexclusive,
          worldwide, limited-term license to host, copy, transmit, retrieve, transform,
          display, and otherwise process Customer Content only as reasonably necessary
          to provide, secure, support, and improve the reliability of the Service,
          enforce the Agreement, and comply with law.
        </p>
        <p>
          Customer instructs Provider to process Customer Content as described in the
          Agreement, the approved configuration, Customer&apos;s use of the Service, and
          documented support requests. Customer represents that it has all rights,
          notices, consents, and lawful bases needed for Customer Content, those
          instructions, and every connected source.
        </p>
        <p>
          For Customer Personal Data, Customer is generally the controller or business
          and Provider is the processor or service provider. If Customer is a processor,
          Provider acts as its subprocessor. The incorporated{" "}
          <Link href="/remainframe/legal/data-processing-addendum">
            Data Processing Addendum
          </Link>{" "}
          governs those activities. Provider remains an independent controller for its
          own business contacts, account security, contract, billing, tax, fraud, and
          legal records.
        </p>
        <p>
          Provider does not sell Customer Content or use it for targeted advertising.
          Provider will not intentionally use Customer Content to train a general-purpose
          model for other customers without Customer&apos;s separate written agreement.
          Customer-selected model providers remain governed by their own terms and
          settings.
        </p>
      </LegalSection>

      <LegalSection id="ip" title="7. RemainFrame intellectual property, outputs, and feedback">
        <p>
          Provider and its licensors retain all rights in RemainFrame, the
          Service, software, workflows, documentation, methods, designs, updates,
          generalized know-how, and improvements, excluding Customer Content. Subject to
          the Agreement, Provider grants Customer a limited, nonexclusive,
          nontransferable, nonsublicensable right during the term for Authorized Users to
          use the Service for Customer&apos;s internal business.
        </p>
        <p>
          Customer may not copy, resell, sublicense, reverse engineer, bypass usage or
          access controls, remove proprietary notices, use the Service to build a
          competing product, or access the Service for benchmarking publication without
          written permission, except where a restriction is prohibited by law.
        </p>
        <p>
          As between the parties, Customer may use Output and Provider assigns to
          Customer any rights Provider may have in that Output, in each case only to the
          extent such rights exist and subject to third-party terms. AI-generated
          material may not be protectable, may not be unique, and may resemble content
          generated for others. Provider does not transfer rights in third-party
          material, the Service, or underlying models.
        </p>
        <p>
          Customer grants Provider the feedback license stated in the Website Terms for
          voluntary, nonconfidential suggestions. Customer Content and Confidential
          Information are not feedback.
        </p>
      </LegalSection>

      <LegalSection id="responsible-use" title="8. Responsible use, approvals, and human review">
        <p>
          Customer and its Authorized Users must comply with the{" "}
          <Link href="/remainframe/legal/acceptable-use">Acceptable Use Policy</Link>.
          The Service may produce incorrect, incomplete, biased, outdated, insecure, or
          otherwise unsuitable Output. Models and tools can misunderstand instructions,
          omit context, fabricate facts, or take an unintended step.
        </p>
        <p>
          Customer is responsible for reviewing Output and tool activity before relying
          on it, establishing appropriate permissions and human approvals, and deciding
          whether a proposed action is appropriate. The pilot may not be used to make
          employment, credit, housing, insurance, health, education, legal, government,
          law-enforcement, or other consequential decisions about a person.
        </p>
        <p>
          Customer may not enable autonomous spending, deletion, external messaging, or
          changes to important records unless the specific workflow has an implemented
          human approval path that shows the proposed action to an authorized reviewer
          before execution. A prompt that says to ask first is not by itself an
          implemented approval control.
        </p>
      </LegalSection>

      <LegalSection id="support-security" title="9. Support, security, and incidents">
        <h3>Support access</h3>
        <p>
          Provider personnel may access Customer Content only when reasonably necessary
          to provide requested support, investigate a reliability or security issue,
          maintain the Service, comply with law, or prevent material harm. Access will be
          limited to authorized personnel with confidentiality duties and the minimum
          scope reasonably needed. When practical, Provider will obtain Customer&apos;s
          permission before content-level support access.
        </p>
        <h3>Security</h3>
        <p>
          Provider will maintain the administrative, technical, and organizational
          measures in the incorporated DPA and the customer-specific activation record.
          The Service is not represented as certified under a particular standard.
          Customer remains responsible for its users, devices, provider accounts and
          keys, source data, connected tools, settings, and approval workflows.
        </p>
        <h3>Security incidents</h3>
        <p>
          Provider will notify Customer without undue delay after becoming aware of a
          confirmed Security Incident involving Customer Personal Data, unless law
          prohibits notice. Notice may be provided in phases as facts become available
          and will include information reasonably available about the nature, likely
          consequences, affected data, containment, and contact point. Provider&apos;s
          notice is not an admission of fault.
        </p>
        <p>
          Customer must promptly notify Provider of suspected compromise and cooperate
          in containment. Each party is responsible for notices it is legally required
          to give, with Provider supplying reasonable assistance for Customer&apos;s
          notices where the DPA applies.
        </p>
      </LegalSection>

      <LegalSection id="confidentiality" title="10. Mutual confidentiality">
        <p>
          <strong>Confidential Information</strong> means nonpublic information disclosed
          by one party to the other that is marked confidential or should reasonably be
          understood as confidential, including Customer Content, security information,
          credentials, product design, business plans, and commercial terms.
        </p>
        <p>
          The receiving party will use Confidential Information only to perform or
          exercise rights under the Agreement, protect it using at least reasonable care
          and no less than the care used for its own similar information, and disclose
          it only to personnel, contractors, advisers, and approved providers who need to
          know it and are bound by confidentiality duties.
        </p>
        <p>
          Confidential Information does not include information that the receiving party
          can document was lawfully known without restriction, independently developed
          without use of the information, received lawfully from another source without
          duty, or made public without breach. If disclosure is legally required, the
          receiving party will, when legally permitted, give prompt notice and reasonable
          assistance so the disclosing party may seek protection.
        </p>
        <p>
          These duties continue for five years after disclosure, except that trade
          secrets and Customer Content remain protected for as long as they qualify as
          confidential under applicable law or remain in Provider&apos;s custody under
          the Agreement.
        </p>
      </LegalSection>

      <LegalSection id="fees" title="11. Fees, renewal, cancellation, and taxes">
        <p>
          Customer will pay the fees, in the currency, on the schedule stated in the
          Order Form. Unless the Order Form states otherwise, undisputed invoices are due
          30 days after the invoice date. Customer must raise a good-faith billing
          dispute before the due date and timely pay undisputed amounts. Late amounts may
          accrue interest at the lesser of 1% per month or the maximum lawful rate.
        </p>
        <p>
          Fees are nonrefundable except as expressly stated in the Agreement or required
          by law. Fees exclude sales, use, withholding, and similar taxes. Customer is
          responsible for those taxes except taxes based on Provider&apos;s net income.
          If withholding is legally required, Customer will provide valid documentation.
        </p>
        <p>
          An Order Form must state whether a subscription renews. Before any online
          recurring subscription is offered, the checkout will clearly disclose the
          renewal term, recurring charge, cancellation policy, and required renewal
          notices. A customer who subscribes online will be able to cancel renewal
          through a direct, one-step online cancellation control available through the
          same account interface or a clearly linked online path. A retention offer will
          not obscure or delay that control. Cancellation stops the next renewal and
          takes effect at the end of the paid term unless the Order Form or law provides
          otherwise.
        </p>
      </LegalSection>

      <LegalSection id="term" title="12. Term, suspension, and termination">
        <p>
          The Agreement begins when the applicable Order Form or clickwrap becomes
          binding and continues for its stated term. Either party may terminate for a
          material breach not cured within 30 days after written notice, or within 10
          days for nonpayment. A party may terminate immediately if the other party
          materially breaches confidentiality, misuses intellectual property, becomes
          insolvent, or cannot lawfully continue the Agreement.
        </p>
        <p>
          Provider may suspend affected access to prevent a credible security threat,
          unlawful use, prohibited data processing, material harm, third-party provider
          violation, or continuing nonpayment. Where reasonably possible, Provider will
          give notice and limit suspension to the affected user, integration, or
          function. Provider will restore access after the condition is resolved.
        </p>
        <p>
          On termination, Customer&apos;s right to use the Service ends and each party
          will pay amounts accrued through the termination date. If Customer terminates
          for Provider&apos;s uncured material breach, Provider will refund prepaid fees
          covering the unused terminated period. If Provider terminates for
          Customer&apos;s uncured breach, remaining committed fees become due to the
          extent permitted by law.
        </p>
        <p>
          Provisions that by their nature should survive do survive, including payment,
          intellectual property, confidentiality, data return and deletion, warranty
          disclaimers, indemnity, liability limits, dispute terms, and general terms.
        </p>
      </LegalSection>

      <LegalSection id="return" title="13. Return, deletion, retention, and export">
        <p>
          The Order Form must state the expected runtime retention, available export or
          handoff method, and any transition assistance. Customer is responsible for
          preserving source records and requesting any available export before the end
          of the term.
        </p>
        <p>
          The current Service has no fully verified self-service export and no
          service-wide selective rights or deletion tooling. Provider may provide a
          configuration-specific export or reasonable manual assistance if stated in the
          Order Form. An export may not reproduce model-provider records, Signal history,
          tool-side records, credentials, internal security logs, or data held directly
          in Customer&apos;s third-party accounts.
        </p>
        <p>
          After termination or Customer&apos;s written instruction, Provider will return
          or delete Customer Content as described in the DPA and Order Form, subject to
          technical feasibility, legal holds, fraud and security records, billing
          records, and backups. Provider and infrastructure snapshots or backups may
          retain residual copies until normal rotation, during which they remain
          protected and are not restored except for continuity, recovery, legal, or
          security needs.
        </p>
      </LegalSection>

      <LegalSection id="warranties" title="14. Warranties and disclaimers">
        <p>
          Each party warrants that it has authority to enter the Agreement and will
          comply with laws applicable to its own performance. Provider warrants that any
          expressly purchased professional services will be performed with reasonable
          care and that the Service will materially conform to the applicable Order Form
          during the term.
        </p>
        <p>
          Customer must report a warranty issue with reasonable detail. Provider&apos;s
          first remedy is to correct or reperform the affected Service. If Provider
          cannot do so within a reasonable period, Customer may terminate the affected
          Order Form and receive a refund of prepaid fees for the unused terminated
          period. This is Customer&apos;s exclusive contractual remedy for breach of the
          warranties in this section.
        </p>
        <p>
          EXCEPT FOR THOSE EXPRESS WARRANTIES, THE SERVICE, PILOT FEATURES, OUTPUTS, AND
          THIRD-PARTY COMPONENTS ARE PROVIDED &quot;AS IS&quot; AND &quot;AS
          AVAILABLE.&quot; TO THE FULLEST EXTENT PERMITTED BY LAW, PROVIDER DISCLAIMS
          IMPLIED OR STATUTORY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
          PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, QUIET ENJOYMENT, AND WARRANTIES
          ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.
        </p>
        <p>
          Provider does not warrant uninterrupted or error-free operation, that Output
          is accurate or unique, that the Service will meet every requirement, or that a
          third-party model, channel, tool, or provider will remain available. These
          disclaimers do not limit an express obligation in the DPA or liability that law
          does not permit the parties to disclaim.
        </p>
      </LegalSection>

      <LegalSection id="indemnity" title="15. Customer indemnity">
        <p>
          Customer will defend Provider and its personnel against a third-party claim,
          and indemnify them from resulting damages, judgments, settlements, and
          reasonable legal fees, to the extent the claim arises from:
        </p>
        <ul>
          <li>
            Customer Content, a connected source, or Customer&apos;s instructions
            infringing or misappropriating a third party&apos;s rights;
          </li>
          <li>
            Customer&apos;s unlawful collection, disclosure, or use of personal data;
          </li>
          <li>
            Customer&apos;s material violation of the Acceptable Use Policy; or
          </li>
          <li>
            an action Customer or an Authorized User takes using Output in violation of
            law or the Agreement.
          </li>
        </ul>
        <p>
          This duty does not apply to the extent a claim was caused by Provider&apos;s
          breach, unauthorized modification, or willful misconduct. Provider must give
          prompt notice, allow Customer to control the defense and settlement, and
          provide reasonable cooperation at Customer&apos;s expense. Customer may not
          settle a claim in a way that admits fault by Provider, imposes nonmonetary
          duties on Provider, or fails to fully release Provider without Provider&apos;s
          written consent.
        </p>
      </LegalSection>

      <LegalSection id="liability" title="16. Excluded damages and liability cap">
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW, NEITHER PARTY WILL BE LIABLE UNDER THE
          AGREEMENT FOR INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, PUNITIVE, OR
          CONSEQUENTIAL DAMAGES, OR FOR LOST PROFITS, REVENUE, SAVINGS, GOODWILL, OR
          BUSINESS OPPORTUNITY, EVEN IF ADVISED THAT THOSE DAMAGES ARE POSSIBLE.
        </p>
        <p>
          EXCEPT FOR THE CARVE-OUTS BELOW, EACH PARTY&apos;S TOTAL AGGREGATE LIABILITY
          ARISING FROM OR RELATED TO THE AGREEMENT WILL NOT EXCEED THE FEES PAID OR
          PAYABLE BY CUSTOMER UNDER THE AFFECTED ORDER FORM DURING THE SIX MONTHS
          IMMEDIATELY BEFORE THE FIRST EVENT GIVING RISE TO LIABILITY. MULTIPLE CLAIMS DO
          NOT INCREASE THE CAP.
        </p>
        <p>
          The excluded-damages waiver and cap do not apply to Customer&apos;s payment
          obligations, either party&apos;s fraud or willful misconduct, breach of mutual
          confidentiality, misappropriation of the other party&apos;s intellectual
          property, Customer&apos;s indemnity obligations, or liability that applicable
          law does not permit to be limited. The parties acknowledge that these
          allocations are a material basis of the fees and Agreement.
        </p>
      </LegalSection>

      <LegalSection id="law" title="17. Governing law, venue, and jury waiver">
        <p>
          Colorado law governs the Agreement without regard to conflict-of-law rules.
          Any court proceeding arising from or related to the Agreement must be brought
          exclusively in the state courts located in Archuleta County, Colorado, or, if
          federal jurisdiction exists, the federal court serving Archuleta County. Each
          party consents to personal jurisdiction and venue there.
        </p>
        <p>
          TO THE FULLEST EXTENT PERMITTED BY LAW, EACH PARTY KNOWINGLY AND VOLUNTARILY
          WAIVES A TRIAL BY JURY IN ANY ACTION ARISING FROM OR RELATED TO THE AGREEMENT.
          THESE SERVICE TERMS DO NOT REQUIRE ARBITRATION AND DO NOT CONTAIN A
          CLASS-ACTION WAIVER.
        </p>
      </LegalSection>

      <LegalSection id="general" title="18. General terms and notices">
        <p>
          Neither party is liable for delay caused by events beyond its reasonable
          control, except that this does not excuse payment already due or obligations
          that reasonably could have been protected through the agreed continuity
          measures. The parties are independent contractors. The Agreement creates no
          partnership, franchise, fiduciary, agency, or employment relationship.
        </p>
        <p>
          Neither party may assign the Agreement without the other&apos;s written
          consent, not to be unreasonably withheld, except to an affiliate or in
          connection with a merger, reorganization, or sale of substantially all assets
          relevant to the Agreement, provided the assignee assumes the obligations and
          is not a direct competitor of the nonassigning party. An invalid provision will
          be enforced to the maximum lawful extent and the remainder will continue.
          Waivers must be written and apply only to the identified instance.
        </p>
        <p>
          The Agreement is the entire agreement on its subject and supersedes prior
          proposals and discussions. Amendments must be signed by authorized
          representatives, except a properly executed renewal Order Form or fixed-version
          clickwrap may incorporate an updated version. Provider will not impose a
          material mid-term change merely by updating this webpage.
        </p>
        <p>
          Operational notices may be sent to the contacts in the Order Form. Formal
          legal notices must be in writing and delivered using the legal names, email
          addresses, and postal notice addresses stated in the signed Order Form. The
          Provider&apos;s notice identity is not replaced by the RemainFrame product name
          or the public hello@dade.studio contact.
        </p>
      </LegalSection>
    </LegalDocument>
  );
}
